# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check-jsons
        run: |
          sudo apt-get install -y json-glib-tools
          json-glib-validate dialogue/*json
          json-glib-validate npcs/*json
          json-glib-validate vn-scene/*json
          json-glib-validate items/*json
          json-glib-validate *json
          
