# This is a basic workflow to help you get started with Actions

name: releaser

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: snickerbockers/submodules-init@v4
      
      - name: Run a multi-line script
        run: |
          rm -rvf .git
          mkdir ../sukeban_I_use_Arch_BTW
          cp -rf * ../sukeban_I_use_Arch_BTW/
          mv ../sukeban_I_use_Arch_BTW .
          cp -rf sukeban_I_use_Arch_BTW sukeban_windows
          wget -q https://github.com/cosmo-ray/yirl/releases/download/latest/yirl-mods.tar.gz
          wget -q https://github.com/cosmo-ray/yirl/releases/download/latest_win/yirl.zip
          mv yirl-mods.tar.gz sukeban_I_use_Arch_BTW
          cd sukeban_I_use_Arch_BTW
          tar -xf yirl-mods.tar.gz
          rm yirl-mods.tar.gz
          echo '#!/bin/sh' > auto-update.sh
          echo 'curl https://github.com/cosmo-ray/Sukeban/releases/download/latest/sukeban_I_use_Arch_BTW.tar.gz -LJO update-tmp.tar.gz' >> auto-update.sh
          chmod +x auto-update.sh
          echo sukeban_I_use_Arch_BTW
          echo '#!/bin/bash' > sukeban.sh
          chmod +x sukeban.sh
          echo yirl/yirl-loader.sh -d ./ -n Sukeban -P yirl/ > sukeban.sh
          cd ..
          mv yirl.zip sukeban_windows
          cd sukeban_windows
          mkdir tmp
          mv yirl.zip tmp
          cd tmp
          unzip yirl.zip
          cd ..
          mv tmp/modules/* modules/
          rm -rvf tmp/modules
          mv tmp/* .
          rm -rvf tmp
          mv yirl-loader.exe Sukeban.exe
          # it seems sazanami is out on windows, so no japanese for its users.
          rm sazanami-mincho.ttf
          cp DejaVuSansMono.ttf sazanami-mincho.ttf
          rm yirl.zip
          cd ..
          tar cfz  sukeban_I_use_Arch_BTW.tar.gz ./sukeban_I_use_Arch_BTW/
          zip -r sukeban_windows.zip ./sukeban_windows/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            sukeban_I_use_Arch_BTW.tar.gz
            sukeban_windows.zip
