# This is a basic workflow to help you get started with Actions

name: releaser

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          rm -rvf .git
          mkdir ../sukeban_I_use_Arch_BTW
          cp -rf * ../sukeban_I_use_Arch_BTW/
          mv ../sukeban_I_use_Arch_BTW .
          cp -rf sukeban_I_use_Arch_BTW sukeban_windows
          wget -q https://github.com/cosmo-ray/yirl/releases/download/latest/yirl.tar.gz
          wget -q https://github.com/cosmo-ray/yirl/releases/download/latest_win/yirl.zip
          mv yirl.tar.gz sukeban_I_use_Arch_BTW
          cd sukeban_I_use_Arch_BTW
          tar -xvf yirl.tar.gz
          rm yirl.tar.gz
          echo sukeban_I_use_Arch_BTW
          cd ..
          mv yirl.zip sukeban_windows
          cd sukeban_windows
          echo sukeban_windows
          unzip yirl.zip
          rm yirl.zip
          cd ..
          tar cvfz  sukeban_I_use_Arch_BTW.tar.gz ./sukeban_I_use_Arch_BTW/
          #zip -r sukeban_windows.zip ./sukeban_windows/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            sukeban_I_use_Arch_BTW.tar.gz
            sukeban_I_use_Arch_BTW.zip
            sukeban_windows.zip
